#!/bin/bash

buildPWD=$installPWD/build

#dependencies
DEPENDENCIES_DIR=$installPWD/dependencies
DEPENDENCIES_TPL_DIR=${DEPENDENCIES_DIR}/tpl_dir
DEPENDENCIES_CERT_DIR=${DEPENDENCIES_DIR}/cert
DEPENDENCIES_COMMON_DIR=${DEPENDENCIES_DIR}/common
DEPENDENCIES_JAR_DIR=${DEPENDENCIES_DIR}/jar
DEPENDENCIES_SOLC_DIR=${DEPENDENCIES_JAR_DIR}/solc
DEPENDENCIES_GMTLS_DIR=${DEPENDENCIES_JAR_DIR}/bctls-gm

#FOLLOW
FOLLOW_DIR=$buildPWD/follow
CHAIN_CERT_DIR=${FOLLOW_DIR}/cert
