#${SECURE_KEY_TPL}
name= ${CHAIN_NODE_NAME_TPL}
agency= ${CHAIN_NODE_AGENCY_TPL}
caHash= ${CHAIN_NODE_CAHASH_TPL}
nodeIdPrivateKey= ${CHAIN_NODE_PRIVKEY_TPL}
nodeId= ${CHAIN_NODE_ID_TPL}
#publicKey= ${CHAIN_NODE_PUBKEY_TPL}

#${CIPHER_KEY_TPL}
nodeEncryptKey= ${CHAIN_NODE_ENCRYPT_KEY_TPL}
